# Generated by Django 4.2.16 on 2025-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[("A", "A형"), ("B", "B형"), ("O", "O형"), ("AB", "AB형")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="chronic_diseases",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_medications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="drinking_average_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="drinking_frequency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="drinking_status",
            field=models.CharField(
                blank=True,
                choices=[("NONE", "비음주"), ("DRINKER", "음주")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="exercise_duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="exercise_frequency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="exercise_status",
            field=models.CharField(
                blank=True,
                choices=[("NONE", "운동 안 함"), ("YES", "운동 함")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="exercise_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="family_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="medical_checkup_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="rh_factor",
            field=models.CharField(
                blank=True,
                choices=[("+", "Rh+"), ("-", "Rh-")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="smoking_daily_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="smoking_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "비흡연"),
                    ("PAST", "과거 흡연"),
                    ("CURRENT", "현재 흡연"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="surgery_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="vaccination_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
